name: Create release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
    timeout-minutes: 15
